<!DOCTYPE html>
<html>
<head>
    @include('Layout.head')


</head>
<body>

@include('Layout.header')

<link rel="stylesheet" type="text/css" href="{{ asset('css/muindustries.css') }}" >

<main id="main">

	<!--==========================

      Services-section-Start

============================-->

	<section id="muindustries-main" class="mu-industries-bg">

		<div class="container-fluid">

			<div class="muser-main-heading">

				<h1>industries</h1>

				<div class="See-btn"> <a href="#about" class="btn-get-started scrollto">Get Started!</a>

				</div>

			</div>

		</div>

	</section>

	<!-- # Services headS section -->

	<!--==========================

      MUservices-detail-section

    ============================-->

	<section id="muindustries-detail-section" class="industries-icon-section">

		<div class="container-fluid">

			<div class="container">

				<div class="row services-detail-sec">

					<div class="col-lg-4">

						<div class="detail-icon">

							<img src="{{asset('img/ind-education.png')}}">

						</div>

					</div>

					<div class="col-lg-8">

						<div class="sevice-heading-para">

							<div class="serv-heading">

								<h2>education</h2>

							</div>

							<div class="services-detail-para">

								<p>Education is one of the most important factors to success and everyone can understand its importance. There are so many possibilities to explore the education industry, with a purpose of serving as well as to facilitate the existing institutions. We can develop and design your educational institution’s website. Our experts can perform search engine optimization strategies to make it top in the online search queries. We can make your education plans and objects all viral on social media with new ideas generated by our social media experts.  Be with us and let’s get started on making your institution an inspiration for students..!!</p>

							</div>

						</div>

					</div>

				</div>

				<!-- # web development section -->

				<div class="row services-detail-sec">

					<div class="col-lg-12 tab-desk-hide">

						<div class="detail-icon">

							<img src="{{asset('img/ind-surgeon.png')}}">

						</div>

					</div>

					<div class="col-lg-8">

						<div class="sevice-heading-para">

							<div class="serv-heading">

								<h2>healthcare</h2>

							</div>

							<div class="services-detail-para">

								<p>MavenUp Creatives understands the virtual presence of healthcare facilities. How can your potential clients call you for early appointments in the general medical fields, dentistry, hospitals, pharmacy billing and orders? You can ask our digital marketing experts to facilitate your healthcare unit, being into a limelight with their effective policies and strategies. The healthcare business domain is rapidly getting digitalized and you will see the best results for sure. Call us for website design and development or the online marketing afterwards, at any stage. </p>

							</div>

						</div>

					</div>

					<div class="col-lg-4  mob-tab-hide">

						<div class="detail-icon">

							<img src="{{asset('img/ind-surgeon.png')}}">

						</div>

					</div>

				</div>

				<!-- # web designing section -->

				<div class="row services-detail-sec">

					<div class="col-lg-4">

						<div class="detail-icon">

							<img src="{{asset('img/ind-plane.png')}}">

						</div>

					</div>

					<div class="col-lg-8">

						<div class="sevice-heading-para">

							<div class="serv-heading">

								<h2>travel</h2>

							</div>

							<div class="services-detail-para">

								<p>Travel and Tourism business is no longer frequently operated through physical offices. You can find plenty of travel consultants and tour operating firms with the best websites and tour plans. If you are lagging behind in such an exclusive industry, immediately get on board with us to comprehensively discuss your market scope, and what sort of a website or web pages you need us to develop. Apart from a regular discussion, we will also devise a strategy as to how you can bring your travel business into the limelight, with the help of expertise that our SEO technicians carry along. </p>

							</div>

						</div>

					</div>

				</div>

				<!-- # E-commerce section -->

				<div class="row services-detail-sec">

					<div class="col-lg-12 tab-desk-hide">

						<div class="detail-icon">

							<img src="{{asset('img/ind-networking.png')}}">

						</div>

					</div>

					<div class="col-lg-8">

						<div class="sevice-heading-para">

							<div class="serv-heading">

								<h2>Social Media /Restaurant</h2>

							</div>

							<div class="services-detail-para">

								<p>Social Media Marketing is phenomenal in terms of reaching out to a range of potential customers, who were mere audiences before. The social platforms like Facebook, Twitter, Instagram, LinkedIn, Pinterest, Tumblr, etc. could give you an instant boost. Also, these platforms can help to increase the scope of your business to an infinite level with social engagements leading to orders for products and services that you offer on the E-commerce portals or general websites. Keep in touch with our Social Media Managers to thrive and become the best amongst the competitors in any industry that you are in…!!</p>

							</div>

						</div>

					</div>

					<div class="col-lg-4  mob-tab-hide">

						<div class="detail-icon">

							<img src="{{asset('img/ind-networking.png')}}">

						</div>

					</div>

				</div>

				<!-- # software development section -->

				<div class="row services-detail-sec">

					<div class="col-lg-4">

						<div class="detail-icon">

							<img src="{{asset('img/ind-startup.png')}}">

						</div>

					</div>

					<div class="col-lg-8">

						<div class="sevice-heading-para">

							<div class="serv-heading">

								<h2>Start-Ups/Real Estate</h2>

							</div>

							<div class="services-detail-para">

								<p>Business Startups have always been a challenging task even for the industry experts. Each new business venture is vulnerable to enormous risks. We at MavenUp Creatives, make a thorough research of your area with demographics to analyze what your competitors are offering, and the average income range of the inhabitants. We always work on a “We grow together” concept. There is no set framework for every startup; the need to understand the businessman’s psyche is as important as of the clients. Our financial business analysts will roadmap a business prospect that will nicely fit into your initial budget plan. </p>

							</div>

						</div>

					</div>

				</div>

				<!-- # software development section -->

				<div class="row services-detail-sec">

					<div class="col-lg-12 tab-desk-hide">

						<div class="detail-icon">

							<img src="{{asset('img/shopping-cart.png')}}">

						</div>

					</div>

					<div class="col-lg-8">

						<div class="sevice-heading-para">

							<div class="serv-heading">

								<h2>e-commerce</h2>

							</div>

							<div class="services-detail-para">

								<p>E-Commerce Industry in on boom and the trend will not even slowdown in the near future as the ease of access, order placement and payment at the customer’s convenience has made it everyone’s first choice. Life has become so irrationally busy and the virtual tours and platforms are highly in use. Because of all the benefits provided by the ecommerce industry, everyone prefers to shop online and their products being delivered at their homes. Boost your digital presence and earn a significant return on investment with our delightful E-commerce website designs. The search engine ranking of your ecommerce website is also our concern if you avail our SEO Services anywhere in the USA or abroad. </p>

							</div>

						</div>

					</div>

					<div class="col-lg-4  mob-tab-hide">

						<div class="detail-icon">

							<img src="{{asset('img/shopping-cart.png')}}">

						</div>

					</div>

				</div>

				<!-- # software development section -->

				<!-- # software development section -->

				<div class="row services-detail-sec">

					<div class="col-lg-4">

						<div class="detail-icon">

							<img src="{{asset('img/ind-accounting.png')}}">

						</div>

					</div>

					<div class="col-lg-8">

						<div class="sevice-heading-para">

							<div class="serv-heading">

								<h2>finance</h2>

							</div>

							<div class="services-detail-para">

								<p>Finance is considered the backbone of any industry and having sufficient bucks in your side pocket measures the will and vigor of your entrepreneurship. That is the major reason for us to keep a deep knowledge of finance technicalities including us knowing how our effective design can truly reflect and present your financial services to your prospective clients. Also, our software development team can add value to your business with finance based apps and software solutions that are highly in demand these days. </p>

							</div>

						</div>

					</div>

				</div>

				<!-- # software development section -->

				<div class="row services-detail-sec business-intell">

					<div class="col-lg-12 tab-desk-hide">

						<div class="detail-icon">

							<img src="{{asset('img/ind-chip.png')}}">

						</div>

					</div>

					<div class="col-lg-8">

						<div class="sevice-heading-para">

							<div class="serv-heading">

								<h2>Business Intelligence /Security & Surveillance</h2>

							</div>

							<div class="services-detail-para">

								<p>The Business Intelligence Solutions are subject to case sensitive software, modules and mobile apps. You can get virtual spreadsheets of the budgets, timesheets, employee records, payroll, attendance charts, and financial calculators for pre-assessment of leaping out for a new business. If you want to expand the existing business then our finance experts, business analyst team along with the software developers will have a meeting with you. They will understand your business goal, and will be able to guide you properly due to vast experience of developing business intelligence tools for many clients as per requirements. </p>

							</div>

						</div>

					</div>

					<div class="col-lg-4  mob-tab-hide">

						<div class="detail-icon">

							<img src="{{asset('img/ind-chip.png')}}">

						</div>

					</div>

				</div>

				<!-- # software development section -->

				<!-- # software development section -->

				<div class="row services-detail-sec">

					<div class="col-lg-4">

						<div class="detail-icon">

							<img src="{{asset('img/entertainment.png')}}">

						</div>

					</div>

					<div class="col-lg-8">

						<div class="sevice-heading-para">

							<div class="serv-heading">

								<h2>Entertainment</h2>

							</div>

							<div class="services-detail-para">

								<p>The entertainment industry is so vast that one cannot think of plunging into all types of it. The United States M&E Industry is spending billions of US Dollars, and earning more out of it. Once you decide to be into the entertainment industry with a vision to open a film production house, television or radio shows, musical concert organization, event management, book publishing, and lots more, our unique web design and hence the website development, will be subject to your entertainment industry’s interest and trends. On the other hand, our marketing experts will help you make an impact of your production house or any other entertainment hub, amongst the people.</p>

							</div>

						</div>

					</div>

				</div>

				<!-- # software development section -->

				<div class="row services-detail-sec business-intell">

					<div class="col-lg-12 tab-desk-hide">

						<div class="detail-icon">

							<img src="{{asset('img/Sports-and-Gaming.png')}}">

						</div>

					</div>

					<div class="col-lg-8">

						<div class="sevice-heading-para">

							<div class="serv-heading">

								<h2>Sports & Gaming</h2>

							</div>

							<div class="services-detail-para">

								<p>MavenUp Creatives comprises of several professional and skilled staff members, who are adept in video game development and maintenance. The sports and gaming industry is vast and you can take the best advantage of this by consulting our experts, who are looking forward to having an impactful growth of your business. With all the in depth consultation and marketing analysis reports, our experts will always guide you the throughout the process to ensure the success you’re looking for. Social media campaigns, Google ads and an E-commerce website will enable the buyers to purchase the online gaming products without any discomfort. </p>

							</div>

						</div>

					</div>

					<div class="col-lg-4  mob-tab-hide">

						<div class="detail-icon">

							<img src="{{asset('img/Sports-and-Gaming.png')}}">

						</div>

					</div>

				</div>

				<!-- # software development section -->

				<div class="col-md-12">

					<div class="See-btn"> <a href="#about" class="btn-get-started scrollto see-btn">Let’s get Started!</a>

					</div>

				</div>

			</div>

		</div>

	</section>

	<!-- MUservices-detail-section -->

	<!--==========================

      MUservices-detail-section

    ============================-->

	<section id="muindustries-digital-section" class="digital-marketting-section">

		<div class="container-fluid">

			<div class="container">

				<div class="row">

					<div class="col-lg-12 col-md-12 col-sm-12 col-xs-12">

						<div class="digital-full-text">

							<div class="digital-text">

								<h2>collab</h2>

							</div>

							<div class="marketing-text">

								<h3>with maven up</h3>

							</div>

						</div>

						<div class="See-btn"> <a href="#about" class="btn-get-started scrollto see-btn">Start A Venture Together</a>

						</div>

					</div>

					<div class="col-lg-8 col-md-8 col-sm-12 col-xs-12">

						<div class="digital-full-text"></div>

					</div>

				</div>

			</div>

		</div>

	</section>

	<!-- MUservices-detail-section -->

<!--==========================
    Footer
  ============================-->
@include('Layout.footer')

</main>
</body>